
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tete5423/microservices-spring-cloud-1-alura
          search-paths: microservices-repo/fornecedor
